server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://192.168.1.233:6603/blzo_friend?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: blzo_friend
    password: 123456

logging:
  level:
    root: info
