server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://192.168.1.233:6603/blzo_friend?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: blzo_friend
    password: 123456

logging:
  level:
    root: info

feign:
  app-friend: blzo-microservice-k8s-app-friend-service:8001
  app-user: blzo-microservice-k8s-app-user-service:8002