spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev # 默认使用开发的配置

# Mybatis配置（可以不使用mybatis-config.xml）
mybatis:
  mapperLocations: classpath:mapper/*.xml

# logback配置
logging:
  file: /tmp/logs/blzo-core.log





