server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.233:6603/blzo_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: blzo_demo
    password: blzo_demo

  redis:
    host: host
    port: 6379
    password: pwd
    database: 0

logging:
  level:
    root: info
