# 内置tomcat端口

spring:
  datasource:
    # 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initSQL: set names utf8mb4
    # 连接池
    initialSize: 5 # 初始化大小
    minIdle: 5 # 最小
    maxActive: 20 # 最大
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jackson: # 返回时间格式正确
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  profiles:
    active: dev # 默认使用develop的配置


  # mvc
  # Path pattern used for static resources.
  mvc:
    static-path-pattern: /**

  # resource
  # 是否开启默认的资源处理，默认为true
  resources:
    add-mappings: true
    chain:
      cache: true # 是否开启缓存，默认为: true
      strategy:
        content:
          enabled: true # 是否开启内容版本策略，默认为false
    # 指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  thymeleaf: #thymeleaf
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: true


# Mybatis配置（可以不使用mybatis-config.xml）
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true


# logback配置
logging:
  file: /tmp/logs/blzo-manage.log

blzo:
  project_name: BLZO
  authj:
    controller-package_name: com.jdkhome.blzo.manage.controller




