server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://192.168.1.233:6603/blzo_user?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: blzo_user
    password: 123456

logging:
  level:
    root: info
