server:
  port: 8081

spring:
  datasource:
    # 应用服务数据源配置
    core:
      url: jdbc:mysql://192.168.1.233:6603/blzo_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: blzo_demo
      password: blzo_demo
    # 管理后台数据源配置(仅供测试，定时重置，请勿搞事)
    manage:
      url: jdbc:mysql://192.168.1.233:6603/blzo_manage?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: blzo
      password: 123456

  redis:
    host: host
    port: 6379
    password: pwd
    database: 0

  #测试时不需要缓存，方便调试
  thymeleaf:
    cache: false

logging:
  level:
    root: info
