spring:
  profiles:
    active: local # 默认使用本地配置
  application:
    name: app-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
        seata:
          tx-service-group: blzo_tx

# Mybatis配置（可以不使用mybatis-config.xml）
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: io.seata.sample.entity

# logback配置
#logging:
#  file: /tmp/logs/app-user.log

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
feign:
  httpclient:
    connection-timeout: 60000


